import { BarChart3, BookOpen, GitBranch, PenLine } from '@lucide/vue'

export const assistantModes = [
  {
    key: 'policy',
    label: '制度问答',
    desc: '查询制度依据',
    title: '环宝 AI 智能助手',
    icon: BookOpen,
    badge: '公司制度知识库',
    welcomeTitle: '您好，我是环宝制度问答助手。',
    welcomeDesc:
      '可为您查询公司内部制度、管理办法和流程规范，支持差旅费、公务用车、审批要求、报销标准等制度问题解答。',
    guideText: '很高兴为您服务！您可以这样查询制度：',
    placeholder: '请输入您要查询的制度问题...',
    suggestions: [
      '差旅费包括哪些费用？',
      '出差住宿费和伙食补助标准是多少？',
      '公务用车如何申请？',
    ],
    capabilities: ['制度查询', '报销标准', '审批规则'],
    capabilityLabel: '查制度 · 找依据',
    apiMode: 'dify',
  },
  {
    key: 'office-ai',
    label: '办公智能',
    desc: '处理办公材料',
    title: '环宝 AI 智能助手',
    icon: PenLine,
    badge: '办公材料处理',
    welcomeTitle: '您好，我是环宝办公智能助手。',
    welcomeDesc: '可协助您整理会议纪要、润色汇报材料、生成工作总结、草拟通知公告和提炼文档摘要。',
    guideText: '很高兴为您服务！您可以这样处理办公材料：',
    placeholder: '请输入您要处理的办公内容...',
    suggestions: [
      '帮我整理一份会议纪要',
      '帮我润色一段事项审批说明',
      '帮我生成一份本周工作总结',
    ],
    capabilities: ['会议纪要', '材料润色', '工作总结'],
    capabilityLabel: '写材料 · 提效率',
    apiMode: 'dify',
  },
  {
    key: 'workflow',
    label: '流程助手',
    desc: '定位业务流程及系统入口',
    title: '环宝 AI 智能助手',
    icon: GitBranch,
    badge: '流程办理助手',
    welcomeTitle: '您好，我是环宝流程助手。',
    welcomeDesc: '可以帮助您查找业务流程及系统入口，并打开当前已开放的流程。',
    guideText: '很高兴为您服务！您可以这样办理业务事项：',
    placeholder: '请输入您要办理的流程事项...',
    suggestions: ['打开采购请示单', '发起合同评审流程', '查看我的待办任务'],
    capabilities: ['打开表单', '发起流程', '待办定位'],
    capabilityLabel: '办流程 · 找入口',
    apiMode: 'mock',
  },
  {
    key: 'data-query',
    label: '智能问数',
    desc: '查询生产指标数据',
    title: '环宝 AI 智能助手',
    icon: BarChart3,
    badge: '生产指标数据查询',
    welcomeTitle: '您好，我是环宝智能问数助手。',
    welcomeDesc: '当前支持生产指标数据查询，可直接描述想查询的指标和时间范围。',
    guideText: '很高兴为您服务！您可以直接查询生产指标和时间范围：',
    placeholder: '请输入您要查询的生产指标...',
    suggestions: [
      '查询本月焚烧量完成情况',
      '查询本月垃圾处理量',
      '查询近三个月发电量变化',
      '查询今年累计生产指标完成情况',
    ],
    capabilities: ['生产指标', '时间范围', '真实数据'],
    capabilityLabel: '当前支持：生产指标',
    apiMode: 'workflow',
  },
]

export const defaultAssistantModeKey = 'policy'
